export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIES__START = 'FETCH_MOVIES__START';
export const FETCH_MOVIES__SUCCESS = 'FETCH_MOVIES__SUCCESS';
export const FETCH_MOVIES__FAILURE = 'FETCH_MOVIES__FAILURE';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const CLEAR_SELECT_MOVIE = 'CLEAR_SELECT_MOVIE';
export const CLEAN_SEARCH_MOVIE = 'CLEAN_SEARCH_MOVIE';